### PR TITLE
Stinger and Elantra SPEC

### PR DESCRIPTION
**Pull request by TK211X**
By request from @WILL and my SPEC

### CODE REVIEW

**Comment by will** [comment]
This is a complete lie. I never requested anything of the sort.

**Comment by TK211X** [comment]
Oh, sorry. Wrong Will.

**Review by emmertex — COMMENTED** [review]
Should keep to 3 decimal places.  Honestly 3 decimal places is going to be more accurate than manufacturing tolerances.

Also are you sure about stinger weight?
According to Kia it is 1780kg.

**Comment by TK211X** [comment]
It's in pounds. Can convert to KG.

**Comment by TK211X** [comment]
Latest Has SPEC data and KG weight for Stinger

**Comment by TK211X** [comment]
Also, looks cooler and more math-y with precise calculated numbers. I like it :)

**Pull request merged**
